# -*- coding: utf-8 -*-
"""Clase8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vf2GQO05MRnItKFveG3T4Tbp5Ir1cTw3
"""



"""<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A : ING PAOLA ANDRA QUINTERO**
#**PRESENTADO POR : Laura Alejandra Colmenares Muñoz**
#**GRADO DECIMO**
#**8 SEPTIEMBRE 2022**

#**¿Qué es Python?**
# Python es un lenguaje de programación multiplataforma y de código abierto que puede utilizarse tanto para desarrollo web, creación de software y procesamiento de datos, entre muchos otros propósitos. Esta versatilidad y facilidad para aprenderlo (es ampliamente considerado el lenguaje más sencillo de aprender) lo han convertido en el lenguaje de programación más popular del mundo, según el índice PYPL.

#**Fecha de lanzamiento y Creadores:** Fue lanzado por primera vez en 1991 por Guido van Rossum y sigue siendo desarrollado hoy en día por la Python Software Foundation.

#**Recuperado de:** https://platzi.com/blog/python/?utm_source=google&utm_medium=cpc&utm_campaign=17739691128&utm_adgroup=&utm_content=&gclid=Cj0KCQjwpeaYBhDXARIsAEzItbHcjinrNmxOXAUu7UMclSNF0hCMR-wwh41Ng74vA0C_sU3sCCwe51oaAvG7EALw_wcB&gclsrc=aw.ds
"""

print("Esto es una suma")
numero_uno= 9
numero_dos= 6
resultado = numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno= 6
numero_dos= 0
resultado = numero_uno - numero_dos
print(resultado)

print("Esto es una Multiplicacion")
numero_uno= 9
numero_dos= 6
resultado = numero_uno * numero_dos
print(resultado)

print("Esto es una División")
numero_uno= 9
numero_dos= 6
resultado = numero_uno / numero_dos
print(resultado)

"""#Ejercicios de Tipos de Datos Simples"""

peso = input("¿Cuál es tu peso en kg? ")
 estatura = input("¿Cuál es tu estatura en metros?")
 imc= round(float(peso)/float(estatura)**2,2)
 print("Tu indece de masa muscular es " + str(imc))

"""## Ejercicio 1
Ecribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla las líneas distintas el nombre del usuario tantas veces como el número introducido
"""

nombre = input("¿Cómo te llamas? ")
n = input("Introduce un número entero: ")
print((nombre + "\n") * int(n))

"""##Ejercicio 2
Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'Tú indice de masa corporal es <imc>' donde '<imc>' es el índice de masa corporal calculado  redondeado  con 2 decimales
"""

peso = input("¿Cúal es tu pesoen Kg? ")
estatura = input("¿Cúal es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Ti índice de masa corporal es " + str(imc))